### ISSUE TITLE
react classnames 

### ISSUE THREAD

**Issue by p-iknow** [p-iknow/tip-archive#82]
https://velog.io/@velopert/react-component-styling

### classnames/bind

classNames 는 CSS 클래스를 조건부로 설정 할 때 매우 유용한 라이브러리입니다. 그리고, CSS Module 을 사용 할 때 이 라이브러리를 함께 사용 한다면 여러 클래스를 적용할 때 편해집니다.

우선, classNames 를 설치하세요:

```bash
$ yarn add classnames
```

한번, classNames 의 기본적인 사용법을 훑어보겠습니다.

```javascript
import classNames from 'classnames';

classNames('one', 'two'); // 'one two'
classNames('one', { two: true }); // 'one two'
classNames('one', { two: false }); // 'one'
classNames('one', ['two', 'three']); // 'one two three'

const myClass = 'hello';
classNames('one', myClass, { myCondition: true }); //'one hello myCondition'

```

이런식으로 여러가지 종류의 파라미터를 조합해 CSS 클래스를 설정 할 수 있게 되기 때문에, 컴포넌트에서 조건부로 클래스를 설정할때 굉장히 편합니다. 예를 들어서 props 의 값에 따라 다른 스타일을 주게 하는게 쉬워지죠:

```javascript
const MyComponent = ({ highlighted, theme }) => {
  <div className={classNames('MyComponent', { highlighted }, theme)}>Hello</div>
}
```

이렇게하면 위 엘리먼트의 클래스로는 highlighted 값이 true 이나 false 에 따라 highlighted 라는 클래스가 적용 될 것이고, 추가적으로 theme 으로 전달받는 문자열이 그대로 클래스에 적용 될 것입니다.

만약에 이런 라이브러리의 도움을 받지 않는다면 이런 형식으로 처리를 하셔야 될 겁니다:

```javascript
const MyComponent = ({ highlighted, theme }) => {
  <div className={`MyComponent ${theme} ${highlighted ? 'highlighted' : ''}`}>Hello</div>
}
```

classNames 를 쓰는 것이 훨씬 가독성이 높지요?

추가적으로, CSS Module 과 함께 쓸 땐 어떻게 편해질 수 있는지 알아보겠습니다.

classNames 를 불러올때 `classnames/bind` 를 사용하면 클래스를 넣어줄 때 마다 `styles.[클래스]` 형식으로 할 필요 없이, 사전에 미리 styles 에서 받아와서 사용하게끔 설정해두고 `cx('class1', 'class2')` 형태로 사용 할 수 있게 됩니다.

한번 CSSModule.js 컴포넌트를 다음과 같이 작성해보세요:

#### src/CSSModule.js

```javascript
import React from 'react';
import classNames from 'classnames/bind';
import styles from './CSSModule.module.css';

const cx = classNames.bind(styles); // 미리 styles 에서 클래스를 받아오도록 설정하고

const CSSModule = () => {
  return (
    <div className={cx('wrapper', 'inverted')}>
      안녕하세요, 저는 <span className="something">CSS Module!</span>
    </div>
  );
};

export default CSSModule;
```

classnames/bind 를 사용하면, CSS Module 을 사용 할 때 클래스를 여러개 설정하거나 또는 조건부로 설정을 하게 될 때, 훨씬 편하게 작성 할 수 있겠죠?

### Sass 와 함께 사용하기

Sass 를 사용할때도 파일이름 뒤에 `.module.scss` 을 입력해주면 CSS Module 로 사용 할 수 있습니다.
한번 파일 이름을 변경해보세요. 스타일 코드도 조금 바꾸겠습니다.

#### CSSModule.module.scss

```scss
/* 자동으로 고유해질 것이므로 흔히 사용되는 단어를 클래스 이름으로 마음대로 사용가능*/

.wrapper {
  background: black;
  padding: 1rem;
  color: white;
  font-size: 2rem;
  &.inverted {
    // inverted 가 .wrapper 와 함께 사용 됐을 때만 적용
    color: black;
    background: white;
    border: 1px solid black;
  }
}

/* 글로벌 CSS 를 작성하고 싶다면 */
:global { // :global {} 로 감싸기
  .something {
    font-weight: 800;
    color: aqua;
  }
  // 여기에 다른 클래스를 만들 수도 있겠죠?
}
```

그리고 CSSModule.js 에서도 상단에 .css 파일 대신 .scss 파일을 불러오세요.

```javascript
import styles from './CSSModule.module.scss';
```

이전과 똑같이 보여지고 있나요?

### CSS Module 이 아닌 파일에서 CSS Module 사용하기

우리가 CSS Module 에서 글로벌 클래스를 정의 할 때 `:global` 을 썼었던 것 처럼, CSS Module 이 아닌 일반 .css/.scss 파일에서도 `:local` 을 통하여 CSS Module 을 사용 할 수도 있습니다.

```css
:local .wrapper {
  /* 스타일 */
}
```

```js
:local {
  .wrapper {
    /* 스타일 */
  }
}
```
